apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-streaming
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      selfHeal: true
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.10.1
    helm:
      values: |
        controller.ingressClass: nginx-streaming
        controller.ingressClassResource.name: nginx-streaming
        controller.ingressClassResource.controllerValue: "k8s.io/nginx-streaming"
        controller.replicaCount: 1

        controller.admissionWebhooks.enabled: false
        admissionWebhooks:
          enabled: false

        controller.config.enable-http2: "false"
        controller.config.proxy-http-version: "1.1"
        controller.config.use-forwarded-headers: "true"

        defaultBackend.enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx-streaming
